# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'ACRT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LeanCloud'
  # Pods for ACRT

end
